// <auto-generated />
namespace ContractsV4._0.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addGovnoTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addGovnoTable));
        
        string IMigrationMetadata.Id
        {
            get { return "202107160552111_addGovnoTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
